### ISSUE TITLE
Get the number from the structured message

### ISSUE THREAD

**Issue by kouinkouin** [netsensei/be-bank-transfer-message#2]
Hi,

If we set a number, we can get the structured message, but if we set only a structured message, we cannot get the number.
Maybe have a method `retrieveNumber()` could do the job ?

**Comment by netsensei** [comment]
I'm sorry I couldn't address this issue sooner due to other work related obligations. It's been a few months.

However, there was no need for you to fork the project and re-publish this package on Packagist - a mere 15 days after opening this issue - under your own name, despite the fact that this project was released under a MIT license.

The appropriate thing would have been to flag my attention with another comment in this issue (or in a separate issue), asking me publicly if this project was still actively maintained. That would have given me a chance to address the urgency of this issue, or to consider relinquishing the ownership of this project to you.

We are now in a very uncomfortable situation where two packages with the exact same code is published on Packagist, since I still actively maintain this project unless otherwise explicitely noted in the README.md or in an open issue seeking new maintainers.

I have merged your pull request. Closing this issue now.
